### ISSUE TITLE
As an operator, I want to update to v13.0.0 of cf-release and test the breaking changes (8/5)

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/cg-deploy-cf#487]
# UNBLOCKED!!! 

**It looks like 13.9 should work.**

_Blocked on https://github.com/cloudfoundry/loggregator-agent-release/issues/35 [13 July 2020]

The 13.6 release notes are not correct: https://github.com/cloudfoundry/cf-deployment/issues/893#issuecomment-657809423

See: https://github.com/cloudfoundry/cf-deployment/releases/tag/v13.0.0

Still blocked in 13.7: https://github.com/cloudfoundry/cf-deployment/releases/tag/v13.7.0_

**Comment by bengerman13** [comment]
review these things, based on the release notes:
Manifest Updates
Changes	Details
- [ ] Removed unused variable cf_bosh_password	If you're using ops file to target this property, your deployment will fail
- [ ] Inlined metrics discovery into the base manifest	Platform engineers can now discover Prometheus-scrapeable metrics endpoints across their foundations through NATs so that they can scrape metrics instead of ingesting Loggregator Envelopes from the Firehose. This change adds two new add-ons to every VM in Cloud Foundry. For more details and reference, please visit Agent Architecture documentation. Operator impact: If your VMs are operating at full or near capacity, you may need to increase the VM resources.
- [ ] Defaults to syslog agents and remove syslog adapters	Replaces the scalable syslog architecture with the shared-nothing syslog architecture. This architecture is more efficient and will enable the usage of the aggregate drains feature. This change adds two new add-ons to every VM in Cloud Foundry. Operator impact: If your VMs are operating at full or near capacity, you may need to increase the VM resources. If you want this change to occur without logs on app syslog drains being duplicated or dropped for much of the duration of the deploy, we recommend deploying v12 with the operations/experimental/add-disabled-syslog-agent-for-upgrade.yml ops file before deploying v13. This ops file is only needed for your last deployment of v12, and is not needed when deploying v13.
- [ ] Allows api and worker instance groups to deploy in parallel	Fixes the issue (CC-Worker should fail/stop if a migration is not completed yet). It also speeds up all cf-d deployments by deploying api and worker instance groups in parallel
New Ops-files
- [ ] operations/experimental/disable-logs-in-firehose.yml
- [ ] operations/experimental/disable-logs-in-firehose-windows2019.yml	Operators can now turn off logs to firehose, allowing them to scale down the doppler and traffic controller/rlp components
Updated Ops-files
- [ ] operations/backup-and-restore/enable-restore-nfs-broker.yml
- [ ] operations/enable-nfs-volume-service.yml	Removed vestigial database and related properties from NFS ops files
- [ ] operations/experimental/use-logcache-syslog-ingress.yml
- [ ] operations/experimental/use-logcache-syslog-ingress-windows2019.yml	Updated logcache syslog ingress to still include metrics
Deleted Ops-file
- [ ] operations/cf-syslog-skip-cert-verify.yml	Removed in favor of inlining syslog agents
- [ ] operations/windows2016-cell.yml	Removed support for Windows Server 1709 cells
- [ ] operations/use-latest-windows1803-stemcell.yml
- [ ] operations/experimental/add-syslog-agent-windows1803.yml
- [ ] operations/experimental/add-system-metrics-agent-windows1803.yml
- [ ] operations/experimental/enable-routing-integrity-windows1803.yml
- [ ] operations/experimental/set-cpu-weight-windows1803.yml
- [ ]operations/experimental/use-logcache-syslog-ingress-windows1803.yml
- [ ]operations/test/remove-logging-pipeline-with-danger-windows1803.yml
- [ ]operations/use-latest-windows1803-stemcell.yml
- [ ]operations/use-offline-windows1803fs.yml
- [ ]operations/windows1803-cell.yml	Removed files related to a deprecated cf stack. Windows 1803
- [ ]operations/use-latest-windows2012R2-stemcell.yml
- [ ]operations/windows2012R2-cell.yml	Removed files related to a deprecated cf stack. Windows 2012R2
- [ ]operations/experimental/disable-uaa-client-redirect-uri-legacy-matching-mode.yml	The ops file is not used by UAA anymore
- [ ]operations/experimental/use-logcache-for-cloud-controller-app-stats.yml
- [ ]operations/experimental/add-credhub-lb.yml
- [ ]operations/experimental/use-logcache-for-cloud-controller-app-stats.yml	It was deprecated in the past and is removed in this release
- [ ]operations/experimental/add-syslog-agent.yml
- [ ]operations/experimental/add-metrics-discovery.yml
- [ ]operations/experimental/enable-suspect-actual-lrp-generation.yml	The contents are inlined into manifest
- [ ]All operations files under operations/bits-service/ folder. See this commit for list of all ops files.	Bit service is no longer maintained

Other Updates
- [ ] Removed workaround directory. The directory is empty.

**Comment by bengerman13** [comment]
The big breaking change, as I read it, is replacing the "scalablesyslog" architecture with the "loggregator-agent" architecture. 
I *think* the changes here are all self-contained, (e.g. we don't need to make any changes to logsearch-for-cloudfoundry, customers with log drains don't need to make changes), but we do need to take some action:
- remove `bosh/opsfiles/syslog-drain.yml` - it's no longer necessary
- figure out how to deal with the transition. We can either lose logs (boo) or have duplication (less boo?) details/options here: https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1588619368046700

**Comment by spgreenberg** [comment]
Here is the recommended order from IBM (https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1589385067061500?thread_ts=1588619368.046700&cid=C2U7KA7M4): 

1) deploy on cfd12.45 with the add-diabled-syslog-agent-for-upgrade
2) deploy to enable the loggr-syslog-binding-cache job on the schedulers.
3) during the above deploy we logged into the adapter VMs and did a monit stop when the agents on the cells started emitting the logs.  This made it so we had a very short period of duplicate logs which we preferred to complete log loss.
4) deploy again (still on cfd12.45) to set the adapters instances to 0 and remove the scheduler job from the scheduler vm (weird) - to remove them from the deployment
5) deploy to upgrade to CFD 13.0.0

I am going through each step now to craft a plan and see what else we need to do to verify this in dev/staging.

**Comment by spgreenberg** [comment]
## Step 0

- [ ] **Pause deploy-staging and deploy-prod jobs in concourse**: The steps above involved multiple deployments and we need to test the end to end rollout without changes in higher environments. Pausing would allow us to do this safely without workarounds. However, this means we cannot deploy stemcell changes during this update process.

**Comment by spgreenberg** [comment]
## Step 1

- *cf-deployment is currently pinned at 12.45*
- [ ] Copy https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/add-disabled-syslog-agent-for-upgrade.yml to https://github.com/cloud-gov/cg-deploy-cf/tree/master/bosh/opsfiles
- [ ] Deploy

**Comment by spgreenberg** [comment]
@bengerman13 We need to alert customers using log drains to a breaking change. What is the process for this? Does statuspage suffice? Would we need to schedule the upgrade because of this?

https://github.com/cloudfoundry/loggregator-agent-release/releases/tag/v6.0.0
```
BREAKING CHANGE: Aggregate drains default to logs only
To re-enable metrics in aggregate drains, append this query parameter to your drain urls: ?include-metrics-deprecated=true
```

**Comment by spgreenberg** [comment]
Development and staging are at v13.6. We need to schedule the prod deploy. A maintenance notice draft is available here: https://docs.google.com/document/d/1EbCOiUMXhya9TYoYqcZUj73MdZB772MhomX9ZBzvmSg/edit?usp=sharing
