### ISSUE TITLE
Implement the new app security group strategy 

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/cg-deploy-cf#580]
In order for spaces to use specific egress rules to lock down or open up access, we must apply the duplicate ASG's to all of the current spaces to keep functionality working as expected before we can remove the global space ASG rule sets. After the duplicate ASG's are applied. We can remove the global ASG's by environment and verify the test suite passes as expected.

## Acceptance Criteria
* [x] Apply new ASG's to all
* [X] Update cg-script org generation to add ASG's and create private spaces
* [X] Create blog post - [PR](https://github.com/cloud-gov/cg-site/pull/2017)
* [x] Remove global ASG's
  * [x] dev
  * [x] staging
  * [x] production 
* [x] Verify tests pass development
* [x] Add passing test validation to deployments before promoting env
* [x] Add tests to staging
* [x]  Add tests to production

--- 

## Security considerations
No change to current spaces but will allow for improved egress control.

## Implementation Details
- Pause CF Terraform for staging and dev
- Update default, global ASG to be a locked down and apply via [TF](https://registry.terraform.io/providers/cloudfoundry-community/cloudfoundry/latest/docs/resources/default_asg)
- Apply and test asg's are working as expected with the asg cli and the test suite
- Unpause for staging and apply the asg cli and the test suite
- Unpause for production and  apply the asg cli and the test suite

**Comment by pburkholder** [comment]
Here's some of my thoughts from a Slack thread today - and now that I see @bengerman13 's comments, we'll need to **check with our customers on whether S3 is needed in spaces they'd otherwise want "closed"**

--
S3 is tricky because even in a space marked “no egress” we’ll still want apps there to reach their brokered  S3 buckets.

But we can’t  do it by IP address because a malicious actor could still get their own S3 govcloud bucket and then use it for exfiltration or C2 (command and control).

So we’ll like have to use something like https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html

If you've already set up access to your Amazon S3 resources from your VPC, you can continue to use Amazon S3 DNS names to access those resources after you've set up an endpoint. However, take note of the following:


and have rules on the VPC s3 gateway for all the S3 buckets we allow egress to:
```
{
  "Effect": "Allow",
  "Action": [
     "s3:ListBucket",
     "s3:GetObject",
     "s3:PutObject"
  ],
  "Resource": [
     "arn:aws:s3:::example-bucket",
     "arn:aws:s3:::example-bucket/*"
  ]
}
```

**Comment by apburnes** [comment]
PR to add different types of egress spaces to new org creation. https://github.com/cloud-gov/cg-scripts/pull/181
